import { pgTable, serial, integer, text, boolean, timestamp } from "drizzle-orm/pg-core";
import { usersTable } from "./users.js";
import { memberSubscriptionsTable } from "./member-subscriptions.js";

/**
 * Audit-trail of renewal reminder messages sent to members. One row per send
 * (manual click in the admin UI or auto-generated by the daily cron). Used to
 * dedupe so the same member isn't pinged twice in 24h, and to surface "last
 * contacted" in the renewals queue.
 */
export const renewalRemindersTable = pgTable("renewal_reminders", {
  id: serial("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => usersTable.id, { onDelete: "cascade" }),
  memberSubscriptionId: integer("member_subscription_id").references(() => memberSubscriptionsTable.id, {
    onDelete: "set null",
  }),
  // Channel keeps things flexible if we add SMS / email later. For now the
  // admin-triggered link send is "whatsapp" and the cron-generated admin
  // notification is "system".
  channel: text("channel").notNull().default("whatsapp"),
  sentBy: text("sent_by").references(() => usersTable.id, { onDelete: "set null" }),
  success: boolean("success").notNull().default(true),
  note: text("note"),
  sentAt: timestamp("sent_at").notNull().defaultNow(),
});

export type RenewalReminder = typeof renewalRemindersTable.$inferSelect;
