import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import sessionsRouter from "./sessions.js";
import auditRouter from "./audit.js";
import usersRouter from "./users.js";
import subscriptionsRouter from "./subscriptions.js";
import trainingRouter from "./training.js";
import logsRouter from "./logs.js";
import paymentsRouter from "./payments.js";
import analyticsRouter from "./analytics.js";
import exportsRouter from "./exports.js";
import importsRouter from "./imports.js";
import expensesRouter from "./expenses.js";
import scheduleRouter from "./schedule.js";
import remindersRouter from "./reminders.js";
import socialRouter from "./social.js";
import waTemplatesRouter from "./wa-templates.js";
import renewalRemindersRouter from "./renewal-reminders.js";
import absenceRemindersRouter from "./absence-reminders.js";
import trainerRouter from "./trainer.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(sessionsRouter);
router.use(auditRouter);
router.use(usersRouter);
router.use(subscriptionsRouter);
router.use(trainingRouter);
router.use(logsRouter);
router.use(paymentsRouter);
router.use(analyticsRouter);
router.use(exportsRouter);
router.use(importsRouter);
router.use(expensesRouter);
router.use(scheduleRouter);
router.use(remindersRouter);
router.use(socialRouter);
router.use(waTemplatesRouter);
router.use(renewalRemindersRouter);
router.use(absenceRemindersRouter);
router.use(trainerRouter);

export default router;
